spring:
  application:
    name: lovable-clone
    description: Lovable Clone in Spring Boot 0 to 100 Course Cohort 4.0


  datasource:
    url: jdbc:postgresql://localhost:5432/testDB
    username: postgres
    password: Root123
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: nqeovnberoipgjhfejfbvsigfieragflWFpfNWRHGOWRNGOWYFBWRAWENFWJQVQACFw

stripe:
  api:
    secret: sk_test_51SwLh3SmRtEtKwn7hfcTzKOOyg2UPMpnUnW54aj9Pvki8rz4aaDFbFKffv2nBRo8nEw0m7AxEyInKuoSyZLbJrsd00ZnDouSgA

client.url: http://localhost:8080

